DOMAIN = "openwrt_mqtt"
DEFAULT_TOPIC_PREFIX = "openwrt/+/"
DEFAULT_TEMPERATURE_UNIT = "°C"
TEMPERATURE_UNITS = ["°C", "°F"]
DISCOVERY_TOPICS = [
    "cpu/load",
    "cpu/load_percent",
    "cpu/temperature",
    "memory/memory-free",
    "memory/memory-cached",
    "memory/memory-used",
    "memory/memory-usage-percent",
    "disk/total",
    "disk/used",
    "disk/free",
    "disk/percent",
    "disk_tmp/total",
    "disk_tmp/used",
    "disk_tmp/free",
    "disk_tmp/percent",
    "conntrack/total",
    "system/hostname",
    "system/model",
    "system/target_platform",
    "system/architecture",
    "system/version",
    "system/uptime",
    "interface-+/if_octets",
    "interface-+/if_errors",
    "interface-+/if_dropped",
    "interface-+/if_packets",
    "interface-+/carrier",
    "interface-+/speed",
    "interface-+/ipv4_+",
    "interface-+/ipv6_+",
]
